import os
import time
import argparse
from dotenv import load_dotenv
from google import genai
from google.genai import types


def extract_text(audio_path):
    # Load API key from .env file
    load_dotenv()
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        print("Error: GEMINI_API_KEY not found in .env file.")
        print("Please make sure you have a .env file with GEMINI_API_KEY=your_key_here")
        return

    # Initialize the new genai Client
    try:
        client = genai.Client(api_key=api_key)
    except Exception as e:
        print(f"Error initializing client: {e}")
        return

    print(f"Uploading '{audio_path}' to Gemini...")
    try:
        audio_file = client.files.upload(file=audio_path)
    except Exception as e:
        print(f"Failed to upload file: {e}")
        return

    # Wait for the file to be processed
    print("Waiting for audio processing to complete", end="")
    while audio_file.state.name == "PROCESSING":
        print(".", end="", flush=True)
        time.sleep(2)
        audio_file = client.files.get(name=audio_file.name)

    if audio_file.state.name == "FAILED":
        print("\nError: File processing failed on Gemini's servers.")
        return

    print(
        "\nAudio ready. Extracting text with high accuracy... (this may take a minute or two)"
    )

    prompt = """
    Please provide a highly accurate, word-for-word transcript of this audio file. 
    It is a podcast/conversation generated by NotebookLM.
    
    Requirements:
    1. Capture all the spoken words perfectly.
    2. DO NOT include any speaker labels (e.g., no "Speaker 1:", no "Host 1:", no names). Just provide the continuous raw text of the conversation.
    3. DO NOT include any headings or stage directions.
    4. Include conversational filler words if they are prominent, to maintain the exact speaking style.
    5. Do not summarize; provide the full, unabridged transcript.
    """

    try:
        response = client.models.generate_content(
            model="gemini-2.5-flash", contents=[prompt, audio_file]
        )
        transcript = response.text

        # Save the transcript to a text file
        output_path = audio_path.rsplit(".", 1)[0] + "_transcript.md"
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(transcript)

        print(
            f"\nExtraction complete! Transcript successfully saved to:\n{output_path}"
        )

    except Exception as e:
        print(f"\nError during text generation: {e}")

    finally:
        # Clean up the file from Gemini servers to save space
        try:
            client.files.delete(name=audio_file.name)
            print("Cleaned up temporary audio file from Gemini servers.")
        except:
            pass


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Extract highly accurate text transcript from an audio file using Gemini."
    )
    parser.add_argument(
        "audio_path", help="Path to the audio file (e.g., audio.mp3, podcast.wav)"
    )

    args = parser.parse_args()

    if not os.path.exists(args.audio_path):
        print(f"Error: File '{args.audio_path}' not found.")
    else:
        extract_text(args.audio_path)
