"""
NCERT Class X - AI Resource Generator (Leveled)
Generates resources at three difficulty levels per chapter:
  - Easy:     Simplified content for beginners / concept introduction
  - Moderate: Standard NCERT/CBSE board level (equivalent to existing resources)
  - Expert: HOTS, competitive-exam level, analytical depth

TEAM USAGE

1. Copy this script
2. Add your subject inside SUBJECTS
3. Add chapter PDFs
4. Set GEMINI_API_KEY environment variable
5. Run:

python generate_resources_leveled.py --subject your_subject

Resources generated per level per chapter:
  question_bank.md | detailed_view.md | summary.md | flashcards.json | quiz.md | short_podcast.md | long_podcast.md | video_script.md

Shared resources (already generated by generate_resources.py) are NOT regenerated:
  mindmap, learning_path, podcast_script, youtube_links, course_offerings

Folder structure:
  generated_resources/<subject>/chapter_XX/beginner/
  generated_resources/<subject>/chapter_XX/intermediate/
  generated_resources/<subject>/chapter_XX/advanced/

Usage:
    python generate_resources_leveled.py              # Full run
    python generate_resources_leveled.py --dry-run    # Preview only
    python generate_resources_leveled.py --subject science   # One subject
    python generate_resources_leveled.py --subject english
    python generate_resources_leveled.py --chapter 1  # Specific chapter (all subjects)
    python generate_resources_leveled.py --level easy  # Only one level
"""

import os, json, time, re, sys, argparse
from pathlib import Path

# ── Fix Windows console encoding ───────────────────────────────────────────
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8")

# ── Dependencies check ─────────────────────────────────────────────────────
try:
    import pdfplumber
except ImportError:
    sys.exit("pip install pdfplumber")

try:
    from docx import Document
except ImportError:
    sys.exit("pip install python-docx")

try:
    from google import genai
except ImportError:
    sys.exit("pip install google-genai")

# ── Configuration ──────────────────────────────────────────────────────────
# Set your Gemini API key in your environment before running this script.
# Windows: set GEMINI_API_KEY=your_key_here
# Linux/macOS: export GEMINI_API_KEY=your_key_here
from dotenv import load_dotenv

load_dotenv()

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

if not GEMINI_API_KEY:
    sys.exit(
        "GEMINI_API_KEY environment variable not found. "
        "Set it before running the script."
    )

DEFAULT_GEMINI_MODELS = [
    "gemini-2.5-flash-lite",
    "gemini-2.5-mini",
    "gemini-2.1",
    "gemini-1.5",
]
GEMINI_MODELS = [
    model.strip()
    for model in os.getenv("GEMINI_MODELS", ",".join(DEFAULT_GEMINI_MODELS)).split(",")
    if model.strip()
]
RATE_LIMIT_DELAY = 5  # seconds between API calls (increased for Free Tier 15 RPM limit)

BASE_DIR = Path(".")

# Example:
#
# "biology": {
#     "folder": BASE_DIR / "biology",
#     "chapters": [
#         "bio01.pdf",
#         "bio02.pdf"
#     ],
#     "chapter_names": [
#         "Plant Anatomy",
#         "Plant Physiology"
#     ]
# },
SUBJECTS = {
    "physics": {
        "folder": Path("."),
        "chapters": ["AQM UNIT4.pdf", "5 Characterization Techniques.pdf"],
        "chapter_names": [
            "Advanced Quantum Mechanics Unit 4",
            "Characterization Techniques",
        ],
    },
    "biology": {
        "folder": Path("."),
        "chapters": [
            "Resources 12th chapter 1 bio.docx",
            "Resources 12th chapter 2 bio.docx",
        ],
        "chapter_names": ["Biology Chapter 1", "Biology Chapter 2"],
    },
    "chemistry": {
        "folder": Path("."),
        "chapters": ["12th_chem_2.docx"],
        "chapter_names": ["Chemistry Chapter 2"],
    },
    "science": {
        "folder": BASE_DIR / "ncert class x science",
        "chapters": [f"jesc1{n:02d}.pdf" for n in range(1, 14)],
        "chapter_names": [
            "Chemical Reactions and Equations",
            "Acids, Bases and Salts",
            "Metals and Non-metals",
            "Carbon and its Compounds",
            "Life Processes",
            "Control and Coordination",
            "How do Organisms Reproduce?",
            "Heredity",
            "Light – Reflection and Refraction",
            "Human Eye and Colourful World",
            "Electricity",
            "Magnetic Effects of Electric Current",
            "Our Environment",
        ],
    },
    "english": {
        "folder": BASE_DIR / "ncert class x english",
        "chapters": [f"jeff1{n:02d}.pdf" for n in range(1, 10)],
        "chapter_names": [
            "A Letter to God",
            "Nelson Mandela: Long Walk to Freedom",
            "Two Stories about Flying",
            "From the Diary of Anne Frank",
            "Glimpses of India",
            "Mijbil the Otter",
            "Madam Rides the Bus",
            "The Sermon at Benares",
            "The Proposal",
        ],
    },
}

OUTPUT_ROOT = BASE_DIR / "generated_resources"
LEVELS = ["beginner", "intermediate", "advanced"]

# ── Gemini client ──────────────────────────────────────────────────────────
client = genai.Client(api_key=GEMINI_API_KEY)


# ── Helpers ────────────────────────────────────────────────────────────────


def extract_pdf_text(pdf_path: Path, max_chars: int = 12000) -> str:
    text = ""
    try:
        with pdfplumber.open(pdf_path) as pdf:
            for page in pdf.pages:
                text += (page.extract_text() or "") + "\n"
                if len(text) > max_chars:
                    break
    except Exception as e:
        print(f"  [WARN] PDF read error {pdf_path.name}: {e}")
    return text[:max_chars].strip()


def extract_docx_text(docx_path: Path, max_chars: int = 12000) -> str:
    """
    Extract text from DOCX file.
    Return plain text similar to extract_pdf_text().
    """
    text = ""
    try:
        doc = Document(docx_path)
        for para in doc.paragraphs:
            text += (para.text or "") + "\n"
            if len(text) > max_chars:
                break
    except Exception as e:
        print(f"  [WARN] DOCX read error {docx_path.name}: {e}")
    return text[:max_chars].strip()


def get_model_candidates() -> list[str]:
    return ["gemini-flash-lite-latest"]


def call_gemini(contents, retries: int = 5) -> str:
    models = get_model_candidates()
    for model in models:
        for attempt in range(1, retries + 1):
            try:
                resp = client.models.generate_content(model=model, contents=contents)
                text = resp.text.strip()
                if text:
                    return text
                raise ValueError("Empty response from Gemini")
            except Exception as e:
                wait = 65
                print(
                    f"\n  [WARN] Gemini ({model}) error ({e}), retry {attempt}/{retries} in {wait}s …",
                    end="",
                    flush=True,
                )
                time.sleep(wait)
        print(f"\n  [WARN] Model {model} failed, switching to next available model.")
    return "[ERROR: Gemini API failed]"


def save_json(data, path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def save_md(text: str, path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def load_metadata(path: Path) -> dict:
    if path.exists():
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except Exception:
            pass
    return {}


# ── Level-specific prompts ─────────────────────────────────────────────────

# ---- QUESTION BANK ----


def p_qb_easy(subj, ch, txt):
    return f"""Create an EASY-LEVEL QUESTION BANK for NCERT Class 10 {subj} – "{ch}".
Target audience: Students just beginning to learn this chapter. Focus on recall and basic understanding.

Include:
1. 10 MCQs (straightforward, directly from text, 1 mark each)
2. 5 Very Short Answer questions (1 mark, one-line answers)
3. 5 Fill-in-the-blanks (direct facts/terms)
4. Brief answer key for all questions

Use simple language. No trick questions. Format in clear markdown.

Chapter content (use this as the basis):
"""


def p_qb_moderate(subj, ch, txt):
    return f"""Create a MODERATE-LEVEL QUESTION BANK for NCERT Class 10 {subj} – "{ch}" (CBSE board standard).

Include:
1. 10 MCQs with options A-D and full answer key
2. 10 Short Answer questions (2–3 marks) with model answers
3. 5 Long Answer questions (5 marks) with outline answers
4. 3 HOTS (Higher Order Thinking Skills) questions

Format in structured markdown. This should match standard CBSE exam difficulty."""


def p_qb_expert(subj, ch, txt):
    return f"""Create an EXPERT-LEVEL QUESTION BANK for NCERT Class 10 {subj} – "{ch}".
Target audience: Students preparing for Olympiads, NTSE, JEE Foundation, or high achievers aiming for 100%.

Include:
1. 10 MCQs requiring deep application, analysis, and multi-concept thinking (HOTS level)
2. 5 Case-study / passage-based questions (3–5 marks each)
3. 5 High-difficulty Long Answer questions requiring integration of multiple concepts
4. 3 Challenge questions requiring original thinking, experimental design, or real-world application
5. Answer key with detailed explanations

Format in structured markdown. Questions should be significantly harder than CBSE board standard."""


# ---- DETAILED VIEW ----


def p_dv_easy(subj, ch, txt):
    return f"""Create an EASY-LEVEL DETAILED VIEW for NCERT Class 10 {subj} – "{ch}".
Target: Students who are new to this topic or struggling with it.

Sections:
1. Chapter Overview
2. Key Concepts
3. Definitions and Terminology
4. Important Points
5. Common Mistakes
6. Exam Tips
7. Quick Revision Points

Use simple vocabulary. Avoid jargon. Make it encouraging and approachable."""


def p_dv_moderate(subj, ch, txt):
    return f"""Create a STANDARD-LEVEL DETAILED VIEW for NCERT Class 10 {subj} – "{ch}".
This should match standard CBSE board preparation level.

Sections:
1. Chapter Overview
2. Key Concepts
3. Definitions and Terminology
4. Important Points
5. Common Mistakes
6. Exam Tips
7. Quick Revision Points

Use markdown formatting. This is the core NCERT detailed view."""


def p_dv_expert(subj, ch, txt):
    return f"""Create an EXPERT-LEVEL DETAILED VIEW for NCERT Class 10 {subj} – "{ch}".
Target: Students aiming for Olympiad/NTSE/JEE Foundation or top board scores.

Sections:
1. Chapter Overview
2. Key Concepts
3. Definitions and Terminology
4. Important Points
5. Common Mistakes
6. Exam Tips
7. Quick Revision Points

Be rigorous and detailed. Include scientific reasoning and evidence-based explanations."""


# ---- SUMMARY ----


def p_summary_easy(subj, ch, txt):
    return f"""Write an EASY-LEVEL SUMMARY for NCERT Class 10 {subj} – "{ch}".
Keep it under 100 words. Use very simple, everyday language as if explaining to a younger sibling.
Focus only on the 2–3 most important ideas. Avoid technical jargon."""


def p_summary_moderate(subj, ch, txt):
    return f"""Write a STANDARD-LEVEL SUMMARY for NCERT Class 10 {subj} – "{ch}".
150–200 words, CBSE board style. Cover all key concepts important for the exam.
Use clear, concise language suitable for a Class 10 student."""


def p_summary_expert(subj, ch, txt):
    return f"""Write an EXPERT-LEVEL SUMMARY for NCERT Class 10 {subj} – "{ch}".
250–300 words. Analytical and comprehensive. Cover all topics with depth.
Include: core concepts, underlying scientific/literary principles, connections to broader ideas, 
and significance of the chapter in a larger academic context.
Suitable for a student who wants full mastery."""


# ---- FLASHCARDS ----


def p_fc_easy(subj, ch, txt):
    return f"""Make 10 EASY flashcards for NCERT Class 10 {subj} – "{ch}".
These should cover basic terms, simple definitions, and fundamental facts only.
Each card: front = simple question, back = short direct answer (1–2 sentences max).
Return ONLY a valid JSON array: [{{"front":"...","back":"..."}},...].
No markdown, no explanation — just the JSON array."""


def p_fc_moderate(subj, ch, txt):
    return f"""Make 15 STANDARD flashcards for NCERT Class 10 {subj} – "{ch}".
Cover all key concepts, definitions, formulas, and important exam points at CBSE board level.
Each card: front = question or term, back = complete answer/explanation.
Return ONLY a valid JSON array: [{{"front":"...","back":"..."}},...].
No markdown, no explanation — just the JSON array."""


def p_fc_expert(subj, ch, txt):
    return f"""Make 25 EXPERT flashcards for NCERT Class 10 {subj} – "{ch}".
Include: complex application questions, multi-step reasoning, exceptions/special cases, 
comparative analysis cards, and competitive-exam-style facts.
Each card: front = challenging question/concept, back = detailed explanation with reasoning.
Return ONLY a valid JSON array: [{{"front":"...","back":"..."}},...].
No markdown, no explanation — just the JSON array."""


# ---- QUIZ ----


def p_quiz_easy(subj, ch, txt):
    return f"""Create an EASY-LEVEL QUIZ for NCERT Class 10 {subj} – "{ch}".
Target: Beginners.
Provide exactly 5 easy multiple-choice questions.

Force the quiz output structure:

Question 1
A. 
B. 
C. 
D. 

Correct Answer: 
Explanation: 

Question 2
...

Format in clear markdown."""


def p_quiz_moderate(subj, ch, txt):
    return f"""Create a MODERATE-LEVEL QUIZ for NCERT Class 10 {subj} – "{ch}".
Target: CBSE board standard.
Provide exactly 5 moderate multiple-choice questions.

Force the quiz output structure:

Question 1
A. 
B. 
C. 
D. 

Correct Answer: 
Explanation: 

Question 2
...

Format in clear markdown."""


def p_quiz_expert(subj, ch, txt):
    return f"""Create an EXPERT-LEVEL QUIZ for NCERT Class 10 {subj} – "{ch}".
Target: Olympiad/NTSE/JEE Foundation.
Provide exactly 5 challenging multiple-choice questions (HOTS level).

Force the quiz output structure:

Question 1
A. 
B. 
C. 
D. 

Correct Answer: 
Explanation: 

Question 2
...

Format in clear markdown."""


# ---- SHORT PODCAST ----


def p_sp_easy(subj, ch, txt):
    return f"""Write a 5-minute EASY-LEVEL SHORT PODCAST script for NCERT Class 10 {subj} – "{ch}".
Target: Beginners. Keep the language very simple, use everyday analogies, and focus on the basics.
Include an intro, the main discussion of core concepts, and a brief wrap-up.

Characters:
* Host 1
* Host 2

Podcast output format must be:

Host 1: 
Host 2: 
Host 1: 
Host 2: 

No narrator.
No host.
No stage directions."""


def p_sp_moderate(subj, ch, txt):
    return f"""Write a 5-minute MODERATE-LEVEL SHORT PODCAST script for NCERT Class 10 {subj} – "{ch}".
Target: Standard CBSE students. Cover the standard textbook concepts, important terms, and exam relevance.
Include an intro, main discussion, and a brief wrap-up.

Characters:
* Host 1
* Host 2

Podcast output format must be:

Host 1: 
Host 2: 
Host 1: 
Host 2: 

No narrator.
No host.
No stage directions."""


def p_sp_expert(subj, ch, txt):
    return f"""Write a 5-minute EXPERT-LEVEL SHORT PODCAST script for NCERT Class 10 {subj} – "{ch}".
Target: Advanced students. Discuss deep concepts, advanced applications, and competitive exam level insights.
Include an intro, main discussion, and a brief wrap-up.

Characters:
* Host 1
* Host 2

Podcast output format must be:

Host 1: 
Host 2: 
Host 1: 
Host 2: 

No narrator.
No host.
No stage directions."""


# ---- LONG PODCAST ----


def p_lp_easy(subj, ch, txt):
    return f"""Write a 15-minute EASY-LEVEL LONG PODCAST script for NCERT Class 10 {subj} – "{ch}".
Target: Beginners. Take time to explain concepts slowly, use multiple relatable analogies, and break down the basics step-by-step.
Include a detailed intro, extended discussion with examples, and a comprehensive wrap-up.

Characters:
* Host 1
* Host 2

Podcast output format must be:

Host 1: 
Host 2: 
Host 1: 
Host 2: 

No narrator.
No host.
No stage directions."""


def p_lp_moderate(subj, ch, txt):
    return f"""Write a 15-minute MODERATE-LEVEL LONG PODCAST script for NCERT Class 10 {subj} – "{ch}".
Target: Standard CBSE students. Thoroughly cover all chapter concepts, CBSE-specific tips, common mistakes, and standard examples.
Include a detailed intro, extended discussion, and a comprehensive wrap-up.

Characters:
* Host 1
* Host 2

Podcast output format must be:

Host 1: 
Host 2: 
Host 1: 
Host 2: 

No narrator.
No host.
No stage directions."""


def p_lp_expert(subj, ch, txt):
    return f"""Write a 15-minute EXPERT-LEVEL LONG PODCAST script for NCERT Class 10 {subj} – "{ch}".
Target: Advanced students. Deep dive into the underlying science/logic, cross-chapter connections, advanced applications, and HOTS.
Include a detailed intro, extended deep-dive discussion, and a comprehensive wrap-up.

Characters:
* Host 1
* Host 2

Podcast output format must be:

Host 1: 
Host 2: 
Host 1: 
Host 2: 

No narrator.
No host.
No stage directions."""


# ---- MINDMAP ----


def p_mindmap(subject, chapter, text):
    return f"""Create a hierarchical mindmap for NCERT Class 10 {subject} – "{chapter}".
Extract the core topics, subtopics, and key points to form a logical tree structure.
Return ONLY a valid JSON object. No markdown formatting, no code blocks, no explanations.
The expected JSON structure must match this EXACT format:
{{
  "name": "{chapter}",
  "children": [
    {{
      "name": "Main Topic",
      "children": [
        {{
          "name": "Sub Topic",
          "children": [
            {{
              "name": "Key Point"
            }}
          ]
        }}
      ]
    }}
  ]
}}"""


# ---- VIDEO SCRIPT ----


def p_vs_easy(subj, ch, txt):
    return f"""Write an EASY-LEVEL scene-by-scene AI video script for NCERT Class 10 {subj} – "{ch}".
Target: Beginners. Keep the visuals engaging and simple, focusing on basic concepts with clear, simple narration.

Requirements:
* Total duration approximately 3 minutes
* Optimized for Veo
* Optimized for Gemini Video
* Optimized for Kling
* Optimized for Runway

Visual Prompt must be detailed and cinematic.

Format:

Scene 1
Duration: 
Visual Prompt: 
Narration: 

Scene 2
Duration: 
Visual Prompt: 
Narration: 

Scene 3
..."""


def p_vs_moderate(subj, ch, txt):
    return f"""Write a MODERATE-LEVEL scene-by-scene AI video script for NCERT Class 10 {subj} – "{ch}".
Target: Standard CBSE students. Focus on standard textbook concepts, diagrams, and clear, concise narration suitable for exam prep.

Requirements:
* Total duration approximately 3 minutes
* Optimized for Veo
* Optimized for Gemini Video
* Optimized for Kling
* Optimized for Runway

Visual Prompt must be detailed and cinematic.

Format:

Scene 1
Duration: 
Visual Prompt: 
Narration: 

Scene 2
Duration: 
Visual Prompt: 
Narration: 

Scene 3
..."""


def p_vs_expert(subj, ch, txt):
    return f"""Write an EXPERT-LEVEL scene-by-scene AI video script for NCERT Class 10 {subj} – "{ch}".
Target: Advanced students. Include complex visuals, advanced connections, and fast-paced, insightful narration.

Requirements:
* Total duration approximately 3 minutes
* Optimized for Veo
* Optimized for Gemini Video
* Optimized for Kling
* Optimized for Runway

Visual Prompt must be detailed and cinematic.

Format:

Scene 1
Duration: 
Visual Prompt: 
Narration: 

Scene 2
Duration: 
Visual Prompt: 
Narration: 

Scene 3
..."""


# ── Resource definitions per level ─────────────────────────────────────────

LEVEL_PROMPTS = {
    "beginner": {
        "question_bank": (p_qb_easy, ".md"),
        "detailed_view": (p_dv_easy, ".md"),
        "summary": (p_summary_easy, ".md"),
        "flashcards": (p_fc_easy, ".json"),
        "quiz": (p_quiz_easy, ".md"),
        "short_podcast": (p_sp_easy, ".md"),
        "long_podcast": (p_lp_easy, ".md"),
        "video_script": (p_vs_easy, ".md"),
    },
    "intermediate": {
        "question_bank": (p_qb_moderate, ".md"),
        "detailed_view": (p_dv_moderate, ".md"),
        "summary": (p_summary_moderate, ".md"),
        "flashcards": (p_fc_moderate, ".json"),
        "quiz": (p_quiz_moderate, ".md"),
        "short_podcast": (p_sp_moderate, ".md"),
        "long_podcast": (p_lp_moderate, ".md"),
        "video_script": (p_vs_moderate, ".md"),
    },
    "advanced": {
        "question_bank": (p_qb_expert, ".md"),
        "detailed_view": (p_dv_expert, ".md"),
        "summary": (p_summary_expert, ".md"),
        "flashcards": (p_fc_expert, ".json"),
        "quiz": (p_quiz_expert, ".md"),
        "short_podcast": (p_sp_expert, ".md"),
        "long_podcast": (p_lp_expert, ".md"),
        "video_script": (p_vs_expert, ".md"),
    },
}


# ── Per-chapter processing ─────────────────────────────────────────────────


def process_chapter_level(
    subject_key: str,
    ch_num: int,
    ch_name: str,
    text: str,
    ch_dir: Path,
    level: str,
    meta: dict,
    dry_run: bool,
) -> dict:
    """Generate all 8 resources for a single chapter + level combination."""
    subj = subject_key.capitalize()
    level_dir = ch_dir / level
    level_dir.mkdir(parents=True, exist_ok=True)

    done = meta.get("completed", {}).get(level, [])

    for res_name, (prompt_fn, ext) in LEVEL_PROMPTS[level].items():
        if res_name in done:
            print(f"      [OK] {res_name} ({level}, cached)")
            continue

        tag = f"[{level.upper()}] {res_name}"
        if dry_run:
            print(f"      [--] Would generate: {tag}")
            done.append(res_name)
            continue

        print(f"      [..] {tag} ...", end=" ", flush=True)

        prompt_str = prompt_fn(subj, ch_name, text)
        if subject_key.lower() == "physics":
            if ext == ".json":
                prompt_str += "\n\nCRUCIAL PHYSICS FORMATTING: Use proper LaTeX for any math equations ($E=mc^2$). Ensure the output remains perfectly valid JSON without any markdown formatting blocks."
            else:
                prompt_str += "\n\nCRUCIAL PHYSICS FORMATTING:\n- Use proper LaTeX formatting for mathematical equations ($$E=mc^2$$ for block math, $F=ma$ for inline math).\n- Use standard Markdown tables for data, comparisons, and formulas.\n- Use Mermaid.js syntax (```mermaid) for flowcharts or system diagrams if helpful.\n- Emphasize derivations, conceptual physics reasoning, numerical properties, and physical constants."

        contents_payload = [text, prompt_str] if text else prompt_str
        result = call_gemini(contents_payload)
        time.sleep(RATE_LIMIT_DELAY)

        # --- Podcast Expansion Logic ---
        if res_name in ["short_podcast", "long_podcast"]:
            min_words = 800 if res_name == "short_podcast" else 2200

            while True:
                word_count = len(result.split())
                est_duration = word_count / 150.0

                print(
                    f"\n      [LOG] {res_name}: {word_count} words, ~{est_duration:.1f} mins",
                    end=" ",
                    flush=True,
                )

                if word_count >= min_words:
                    print("- Meets duration requirement.")
                    break

                print(
                    f"- Expanding (target > {min_words} words)...", end=" ", flush=True
                )

                context = result[-1000:]

                expand_prompt = f"""You are continuing a {res_name.replace('_', ' ')}. 
The script so far is {word_count} words long, but it needs to be at least {min_words} words to reach the minimum duration requirement.
Please CONTINUE the script naturally from exactly where it left off. Do NOT write a new introduction or repeat what was already said.
Continue the engaging discussion between Boy and Girl, adding more examples, analogies, and back-and-forth dialogue.

Ensure the format strictly follows:
Host 1: [dialogue]
Host 2: [dialogue]

Previous script ending for context:
{context}"""

                expansion = call_gemini(expand_prompt)
                result += "\n\n" + expansion.strip()
                time.sleep(RATE_LIMIT_DELAY)
        # --- End Podcast Expansion Logic ---

        out_path = level_dir / (res_name + ext)

        if ext == ".json":
            raw = re.sub(
                r"```(?:json)?\s*|\s*```", "", result, flags=re.IGNORECASE
            ).strip()
            try:
                data = json.loads(raw)
                save_json(
                    {
                        "chapter": ch_name,
                        "subject": subj,
                        "level": level,
                        "flashcards": data,
                    },
                    out_path,
                )
            except json.JSONDecodeError:
                # Fall back to saving as markdown if JSON fails
                save_md(result, out_path.with_suffix(".md"))
        else:
            save_md(result, out_path)

        done.append(res_name)
        print("[OK]")

    # Update metadata
    if "completed" not in meta:
        meta["completed"] = {}
    meta["completed"][level] = done
    return meta


def process_chapter(
    subject_key: str,
    ch_index: int,
    pdf_path: Path,
    ch_name: str,
    out_dir: Path,
    levels_to_run: list,
    dry_run: bool,
):
    ch_num = ch_index + 1
    ch_dir = out_dir / f"chapter_{ch_num:02d}"
    ch_dir.mkdir(parents=True, exist_ok=True)

    meta_path = ch_dir / "metadata_leveled.json"
    meta = load_metadata(meta_path)
    if not meta:
        meta = {
            "chapter_number": ch_num,
            "chapter_name": ch_name,
            "subject": subject_key.capitalize(),
            "pdf": pdf_path.name,
            "completed": {},
        }

    subj = subject_key.capitalize()
    print(f"\n  [>>] [{subj}] Ch {ch_num}: {ch_name}")

    if dry_run:
        text = ""
    else:
        suffix = pdf_path.suffix.lower()
        if suffix == ".pdf":
            print(
                f"  [UPLOAD] Uploading {pdf_path.name} to Gemini API for native multimodal processing..."
            )
            try:
                text = client.files.upload(file=str(pdf_path))
                print(
                    f"  [UPLOAD] Waiting for document to process...", end="", flush=True
                )
                while text.state.name == "PROCESSING":
                    time.sleep(2)
                    print(".", end="", flush=True)
                    text = client.files.get(name=text.name)
                if text.state.name == "FAILED":
                    print(f"\n  [ERROR] Document processing failed on Gemini server.")
                    return
                print(" [READY]")
            except Exception as e:
                print(f"\n  [ERROR] Upload failed: {e}")
                return
        elif suffix == ".docx":
            text = extract_docx_text(pdf_path)
        else:
            print(f"  [WARN] Unsupported file type: {suffix}")
            return

        if not text:
            print("     [SKIP] No document content found.")
            return

    # Generate Shared Mindmap
    mindmap_path = ch_dir / "mindmap.json"
    mindmap_md_path = ch_dir / "mindmap.md"
    if mindmap_path.exists() or mindmap_md_path.exists():
        print(f"    [SHARED] mindmap (cached)")
    elif dry_run:
        print(f"    [SHARED] Would generate: mindmap")
    else:
        print(f"    [SHARED] Generating mindmap ...", end=" ", flush=True)
        mm_prompt = p_mindmap(subj, ch_name, text)
        mm_payload = [text, mm_prompt] if text else mm_prompt
        mm_result = call_gemini(mm_payload)
        time.sleep(RATE_LIMIT_DELAY)

        raw_mm = re.sub(
            r"```(?:json)?\s*|\s*```", "", mm_result, flags=re.IGNORECASE
        ).strip()
        try:
            mm_data = json.loads(raw_mm)
            save_json(mm_data, mindmap_path)
            print("[OK]")
        except json.JSONDecodeError:
            save_md(mm_result, mindmap_md_path)
            print("[WARN: Invalid JSON, saved as .md]")

    for level in levels_to_run:
        print(f"    [*] Level: {level.upper()}")
        meta = process_chapter_level(
            subject_key, ch_num, ch_name, text, ch_dir, level, meta, dry_run
        )
        if not dry_run:
            save_json(meta, meta_path)

    print(f"  [DONE] Ch {ch_num} done for levels: {', '.join(levels_to_run)}")


# ── README generator ───────────────────────────────────────────────────────

SHARED_RESOURCES = [
    "mindmap",
    "learning_path",
    "podcast_script",
    "youtube_links",
    "course_offerings",
]

LEVELED_RESOURCES = [
    "question_bank",
    "detailed_view",
    "summary",
    "flashcards",
    "quiz",
    "short_podcast",
    "long_podcast",
    "video_script",
]


def write_index(out_dir: Path, subject: str, chapters: list):
    lines = [f"# NCERT Class 10 {subject.capitalize()} – Study Resources\n\n"]

    for i, ch in enumerate(chapters, 1):
        ch_folder = f"chapter_{i:02d}"
        lines.append(f"## Chapter {i}: {ch}\n\n")

        lines.append("### Shared Resources\n")
        for res in SHARED_RESOURCES:
            # Try .md and .json
            for ext in [".md", ".json"]:
                f = f"{ch_folder}/{res}{ext}"
                if (out_dir / ch_folder / (res + ext)).exists():
                    lines.append(f"- [{res.replace('_',' ').title()}]({f})\n")
                    break

        lines.append("\n### Leveled Resources\n")
        lines.append("| Resource | Easy | Moderate | Expert |\n")
        lines.append("|---|---|---|---|\n")
        for res in LEVELED_RESOURCES:
            ext = ".json" if res == "flashcards" else ".md"
            row = f"| {res.replace('_',' ').title()} |"
            for level in LEVELS:
                path = out_dir / ch_folder / level / (res + ext)
                if path.exists():
                    row += f" [✅]({ch_folder}/{level}/{res}{ext}) |"
                else:
                    row += " ❌ |"
            lines.append(row + "\n")
        lines.append("\n")

    lines.append("## [PYQ Analysis](pyq_analysis/pyq_analysis.md)\n")
    save_md("".join(lines), out_dir / "README.md")
    print(f"  [README] Updated: {out_dir / 'README.md'}")


# ── Main ───────────────────────────────────────────────────────────────────


def parse_args():
    p = argparse.ArgumentParser(description="NCERT Leveled Resource Generator")
    p.add_argument("--dry-run", action="store_true", help="Preview without API calls")
    p.add_argument("--subject", choices=list(SUBJECTS.keys()), help="Only one subject")
    p.add_argument("--chapter", type=int, help="Only this chapter number (1-based)")
    p.add_argument("--level", choices=LEVELS, help="Only this difficulty level")
    return p.parse_args()


def main():
    args = parse_args()

    subjects_to_run = [args.subject] if args.subject else list(SUBJECTS.keys())
    levels_to_run = [args.level] if args.level else LEVELS

    print("=" * 65)
    print("  NCERT Class X | Leveled Resource Generator | Gemini 2.5 Flash")
    print("=" * 65)
    if args.dry_run:
        print("  [DRY-RUN MODE] - no API calls will be made\n")
    print(f"  Subjects : {', '.join(subjects_to_run)}")
    print(f"  Levels   : {', '.join(levels_to_run)}")
    print(f"  Output   : {OUTPUT_ROOT}\n")

    for subject_key in subjects_to_run:
        cfg = SUBJECTS[subject_key]
        out_dir = OUTPUT_ROOT / subject_key

        print(f"\n{'='*65}")
        print(f"  [{subject_key.upper()}]  ({len(cfg['chapters'])} chapters)")
        print(f"{'='*65}")

        for idx, (pdf_name, ch_name) in enumerate(
            zip(cfg["chapters"], cfg["chapter_names"])
        ):
            ch_num = idx + 1
            if args.chapter and ch_num != args.chapter:
                continue

            pdf_path = cfg["folder"] / pdf_name
            if not pdf_path.exists():
                print(f"  [MISSING] {pdf_path}")
                continue

            process_chapter(
                subject_key,
                idx,
                pdf_path,
                ch_name,
                out_dir,
                levels_to_run,
                args.dry_run,
            )

        # Regenerate README with leveled links
        write_index(out_dir, subject_key, cfg["chapter_names"])

    print("\n" + "=" * 65)
    if args.dry_run:
        print("  [OK] DRY-RUN COMPLETE - no files were changed.")
    else:
        print("  [OK] ALL LEVELED RESOURCES GENERATED!")
    print(f"  Output folder: {OUTPUT_ROOT}")
    print("=" * 65)


if __name__ == "__main__":
    main()
